LANG = {
    "ru": {
        "app_title": "ColorCrypt — Текст \u21c4 Изображение (v{})",
        "main_tab": "Главная",
        "settings_tab": "Настройки",
        "security_tab": "Безопасность",
        "batch_tab": "Пакетная обработка",
        "iii_tab": "Картинка в картинке",
        "media_tab": "Медиа (GIF/MP4/MP3/Video)",
        "scanner_tab": "Детектор",
        "debug_tab": "Отладка",
        "mode_frame": "Режим работы",
        "mode_encode": "\U0001f4c4 \u0422\u0435\u043a\u0441\u0442 \u2192 \U0001f5bc \u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 (\u041a\u043e\u0434\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435)",
        "mode_decode": "\U0001f5bc \u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u2192 \U0001f4c4 \u0422\u0435\u043a\u0441\u0442 (\u0414\u0435\u043a\u043e\u0434\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435)",
        "file_frame": "Файл",
        "select_file": "\U0001f4c2 \u0412\u044b\u0431\u0440\u0430\u0442\u044c \u0444\u0430\u0439\u043b",
        "no_file": "Файл не выбран",
        "file_info": "Файл: {} ({})",
        "content_frame": "Содержимое",
        "progress_frame": "Прогресс",
        "ready": "Готов",
        "execute": "\u25b6 \u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u044c",
        "cancel": "\u23f9 \u041e\u0442\u043c\u0435\u043d\u0430",
        "channel_frame": "Режим записи в изображение",
        "channel_mono": "1-канальный (только R) — максимальная совместимость",
        "channel_rgb": "3-канальный (RGB) — хорошее сжатие",
        "channel_rgba": "4-канальный (RGBA) — максимальная плотность",
        "encode_frame": "Режим кодирования данных",
        "encode_base64": "Base64 — совместимый режим",
        "compress_frame": "Сжатие данных (zlib)",
        "compress_enable": "Включить сжатие",
        "compress_level": "Уровень сжатия:",
        "format_frame": "Формат вывода",
        "chunk_frame": "Чанковый режим (для больших файлов)",
        "chunk_enable": "Разделять на чанки",
        "chunk_size": "Размер чанка:",
        "options_frame": "Дополнительные настройки",
        "integrity": "Проверка целостности (SHA-256)",
        "preserve_name": "Сохранять оригинальное имя файла",
        "lsb_label": "LSB-битность (0 = прямой режим):",
        "lsb_hint": "(1-4 = LSB стеганография)",
        "output_dir_frame": "Папка для сохранения",
        "output_dir_btn": "\U0001f4c1 \u0412\u044b\u0431\u0440\u0430\u0442\u044c \u043f\u0430\u043f\u043a\u0443",
        "output_dir_default": "(рядом с исходным)",
        "encrypt_frame": "AES-256-SIV Шифрование",
        "encrypt_enable": "Включить шифрование AES-256-SIV (стойкое к повтору nonce)",
        "password": "Пароль:",
        "confirm": "Подтверждение:",
        "gen_password": "\U0001f512 Сгенерировать пароль",
        "show_password": "Показать пароль",
        "strength_frame": "Сложность пароля",
        "empty_password": "\u274c Пустой пароль",
        "hint_frame": "Подсказка для пароля",
        "hint_warn": "\u26a0\ufe0f Подсказки снижают безопасность! Не указывайте информацию, раскрывающую пароль.",
        "hint_display": "\U0001f4a1 Подсказка: {}",
        "encrypt_info": "\U0001f510 Информация о шифровании:\n\u2022 AES-256-SIV (стойкий к повтору nonce)\n\u2022 Argon2id (GPU-устойчивый, 64MB памяти)\n\u2022 Случайная соль (16 байт)\n\u2022 Встроенная проверка целостности",
        "batch_add": "\u2795 Добавить файлы",
        "batch_clear": "\U0001f5d1 Очистить список",
        "batch_count": "Файлов: {}",
        "batch_list": "Файлы для обработки",
        "batch_encode_all": "\u25b6 Кодировать всё",
        "batch_decode_all": "\u25c0 Декодировать всё",
        "debug_options": "Отладочные опции",
        "debug_mode": "Режим отладки (подробное логирование)",
        "debug_clear": "Очистить лог",
        "iii_container_frame": "1. Контейнер (куда прячем)",
        "iii_select_container": "\U0001f4c2 Выбрать изображение-контейнер",
        "iii_not_selected": "Не выбран",
        "iii_secret_frame": "2. Секретное изображение",
        "iii_select_secret": "\U0001f4c2 Выбрать секретное изображение",
        "iii_options_frame": "3. Опции",
        "iii_use_alpha": "Использовать альфа-канал",
        "iii_restore": "Восстановить контейнер после декодирования",
        "iii_output_frame": "4. Сохранение",
        "iii_select_output": "\U0001f4c1 Выбрать путь сохранения",
        "iii_not_specified": "Не указан",
        "iii_encode_btn": "\u25b6 Закодировать (прячем секрет в контейнер)",
        "iii_decode_btn": "\u25c0 Декодировать (извлечь секрет из контейнера)",
        "iii_result_frame": "Результат",
        "iii_working": "Кодирование Image-in-Image...",
        "iii_decode_working": "Декодирование Image-in-Image...",
        "iii_success": "\u2705 Успех!",
        "iii_saved": "\U0001f4c1 Сохранено: {}",
        "iii_secret_size": "\U0001f532 Размер секрета: {}",
        "iii_alpha_saved": "   Альфа-канал сохранён",
        "iii_container_restored": "\u267b Контейнер восстановлен: {}",
        "iii_error": "\u274c Ошибка: {}",
        "media_codecs": "Доступные кодеки",
        "media_no_codecs": "\u274c Нет доступных кодеков",
        "media_mode_frame": "Режим",
        "media_encode_mode": "Закодировать (спрятать данные в медиа)",
        "media_decode_mode": "Декодировать (извлечь данные из медиа)",
        "media_codec_sel": "Формат медиа",
        "media_install": "Установите imageio или ffmpeg",
        "media_file_frame": "Файл",
        "media_select_input": "\U0001f4c2 Выбрать медиа-файл",
        "media_data_frame": "Файл с данными (для кодирования)",
        "media_select_data": "\U0001f4c2 Выбрать файл с данными",
        "media_output_frame": "Сохранение",
        "media_select_output": "\U0001f4c1 Выбрать путь сохранения",
        "media_execute": "\u25b6 Выполнить",
        "scan_file_frame": "Файл для сканирования",
        "scan_select_file": "\U0001f4c2 Выбрать изображение",
        "scan_opts_frame": "Параметры сканирования",
        "scan_alpha": "Сканировать альфа-канал",
        "scan_rgb": "Сканировать RGB-каналы",
        "scan_depth": "Глубина LSB:",
        "scan_btn": "\U0001f50d Сканировать",
        "scan_result_frame": "Результаты сканирования",
        "scan_working": "Сканирование...",
        "scan_no_results": "\u274c Заголовков ColorCrypt не обнаружено.",
        "scan_no_reasons": "Возможные причины:\n  \u2022 Файл не содержит скрытых данных\n  \u2022 Данные скрыты с другой LSB-глубиной\n  \u2022 Файл был пережат с потерями",
        "scan_found": "\u2705 Найдено заголовков: {}\n\n",
        "scan_channel": "  Канал: {}\n",
        "scan_lsb": "  LSB-слоёв: {}\n",
        "scan_type": "  Тип: {}\n",
        "scan_sig": "  Сигнатура: {}\n",
        "scan_ver": "  Версия: {}\n",
        "scan_sep": "  ---\n",
        "drop_file": "\U0001f4a1 Перетащите файл сюда",
        "drop_btn": "\U0001f4a1 Выберите файл кнопкой",
        "err_file_not_found": "Файл не найден",
        "err_no_file": "Сначала выберите файл",
        "err_encrypt_no_password": "Введите пароль для шифрования",
        "err_password_mismatch": "Пароли не совпадают",
        "err_password_hint": "Файл зашифрован. Введите пароль для расшифровки:",
        "err_batch_password_hint": "Некоторые файлы зашифрованы. Введите пароль для расшифровки:",
        "err_encode_failed": "Ошибка кодирования:\n{}",
        "err_decode_failed": "Ошибка декодирования:\n{}",
        "err_read_failed": "Не удалось прочитать файл:\n{}",
        "err_read_image": "Не удалось прочитать изображение: {}",
        "err_operation_cancelled": "Операция отменена",
        "err_select_container": "Выберите контейнер и секретное изображение",
        "err_select_output": "Укажите путь сохранения",
        "err_media_no_input": "Выберите медиа-файл",
        "err_media_no_data": "Выберите файл с данными",
        "err_scan_no_file": "Сначала выберите файл для сканирования",
        "err_batch_empty": "Сначала добавьте файлы в список",
        "warn_big_file": "Файл большой ({}). Показать содержимое?",
        "warn_large_file": "[Файл слишком большой для предпросмотра]\nРазмер: {}",
        "warn_text_preview": "[Файл содержит {} строк, показаны первые 50]\n\n",
        "warn_more_lines": "\n\n... и ещё {} строк",
        "warn_binary": "[Бинарный файл]\nРазмер: {}\nSHA-256: {}",
        "warn_text_more": "\n\n... и ещё {} строк",
        "encode_success": "\u2705 Кодирование завершено!\n\n",
        "encode_saved": "\U0001f4c1 Сохранено: {}\n",
        "encode_dims": "\U0001f4d0 Размер: {}x{}\n",
        "encode_format": "\U0001f3a8 Формат: {}\n",
        "encode_file_size": "\U0001f4be Размер файла: {}\n",
        "encode_time": "\u23f1 Время: {:.2f} сек\n",
        "encode_chunks": "\n\U0001f4e6 Чанковый режим: {} чанков\n",
        "encode_compress": "\U0001f5dc Сжатие: {}\n",
        "encode_encryption": "\U0001f510 Шифрование: AES-256-SIV + Argon2id\n",
        "encode_hint_warn": "\u26a0\ufe0f ВНИМАНИЕ: Подсказки для пароля небезопасны!\n   Не используйте подсказки, раскрывающие пароль.\n\U0001f4a1 Подсказка: {}\n",
        "encode_sha": "\U0001f511 SHA-256: {}\n",
        "decode_success": "\u2705 Декодирование завершено!\n\n",
        "decode_saved": "\n\n\U0001f4c1 Файл сохранён: {}\n",
        "decode_size": "\U0001f4e6 Размер: {}\n",
        "decode_chunks": "\U0001f4e6 Восстановлено из {} чанков\n",
        "iii_use_alpha_short": "Использовать альфа-канал",
        "iii_restore_short": "Восстановить контейнер",
        "file_loaded": "\u2705 Загружен: {}",
        "image_info": "\U0001f5bc Информация об изображении:\n",
        "image_dims": "  Размер: {}x{}\n",
        "image_mode": "  Режим: {}\n",
        "image_format": "  Формат: {}\n\n",
        "image_decode_hint": "Нажмите 'Выполнить' для декодирования скрытых данных.",
        "cancel_operation": "\u26a0\ufe0f Отмена операции...",
        "select_encode_file": "\U0001f4c2 Выбрать файл для кодирования",
        "select_decode_file": "\U0001f4c2 Выбрать изображение для декодирования",
        "encode_hint": "Поддерживаются любые файлы (текстовые, бинарные)",
        "decode_hint": "Поддерживаются PNG, WebP, BMP, TIFF, AVIF, JPEG, ZIP, созданные ColorCrypt",
        "batch_complete": "Завершено",
        "batch_summary": "Обработано файлов: {}\n\u2705 Успешно: {}\n\u274c Ошибок: {}",
        "password_very_strong": "\U0001f512 Очень сильный",
        "password_strong": "\U0001f510 Сильный",
        "password_medium": "\u26a0\ufe0f Средний",
        "password_weak": "\u26a0\ufe0f Слабый",
        "password_very_weak": "\u274c Очень слабый",
        "password_empty": "\u274c Пустой пароль",
        "password_match": "\u2705 Пароли совпадают",
        "password_no_match": "\u274c Пароли не совпадают",
        "pass_len_ge12": "\u2713 Длина \u226512 символов",
        "pass_len_ge8": "\u2713 Длина \u22658 символов",
        "pass_len_min8": "\u2717 Минимум 8 символов",
        "pass_upper": "\u2713 Есть заглавные буквы",
        "pass_no_upper": "\u2717 Добавьте заглавные буквы",
        "pass_lower": "\u2713 Есть строчные буквы",
        "pass_no_lower": "\u2717 Добавьте строчные буквы",
        "pass_digit": "\u2713 Есть цифры",
        "pass_no_digit": "\u2717 Добавьте цифры",
        "pass_special": "\u2713 Есть спецсимволы",
        "pass_no_special": "\u2717 Добавьте спецсимволы",
        "pass_generated": "\u2705 Случайный пароль сгенерирован и скопирован в буфер",
        "lang_label": "Язык / Language:",
        "theme_label": "Тёмная тема",
        "select_encode": "Выберите файл для кодирования",
        "select_decode_img": "Выберите изображение для декодирования",
        "select_container": "Выберите изображение-контейнер",
        "select_secret": "Выберите секретное изображение",
        "save_as": "Сохранить как",
        "select_media": "Выберите медиа-файл",
        "select_data": "Выберите файл с данными",
        "select_save_as": "Сохранить как",
        "select_scan": "Выберите изображение для сканирования",
        "select_output_dir": "Выберите папку для сохранения",
        "status_ready": "Готов",
        "status_scanning": "\u23f3 Сканирую...",
        "status_error": "\u274c Ошибка",
        "status_not_found": "\u274c Ничего не найдено",
        "status_found_headers": "\u2705 Найдено {} заголовков",
        "media_ready": "Готов",
        "media_working": "\u23f3 Работаю...",
        "media_done": "\u2705 Готово",
        "media_success": "\u2705 Успех!\nСохранено: {}",
        "media_error": "Ошибка: {}",
        "iii_working_short": "\u23f3 Работаю...",
        "iii_done": "\u2705 Готово",
        "notice": "Предупреждение",
        "error": "Ошибка",
        "iii_result_size": "  Размер секрета: {}x{}\n",
        "theme_applied_light": "\u2600\ufe0f Светлая тема",
        "theme_applied_dark": "\U0001f319 Тёмная тема",
        "unit_b": "Б",
        "unit_kb": "КБ",
        "unit_mb": "МБ",
        "unit_gb": "ГБ",
        "unit_tb": "ТБ",
        "adaptive_lsb": "Адаптивный K-LSB (разный битрейт на канал)",
        "k_lsb_r": "R:",
        "k_lsb_g": "G:",
        "k_lsb_b": "B:",
        "k_lsb_a": "A:",
        "zip_mode": "Упаковать чанки в ZIP",
        "salt_label": "Соль (hex, опционально):",
        "salt_hint": "(оставьте пустым для случайной генерации)",
        "entropy_btn": "Анализ LSB-энтропии",
        "entropy_working": "Анализ энтропии...",
        "entropy_result": "Результаты LSB-энтропии\n\n",
        "entropy_channel": "  Канал {0}: {1} нулей / {2} единиц (соотношение: {3:.4f})\n",
        "entropy_chi2": "    χ² = {0:.2f}, p = {1:.4f}\n",
        "entropy_suspicious": "    ПОДОЗРИТЕЛЬНО: распределение слишком равномерно (p > 0.95)\n",
        "entropy_normal": "    Естественное распределение\n",
        "entropy_overall": "\nОбщий вердикт: {0}\n",
        "entropy_level_low": "Низкая — LSB выглядят естественно",
        "entropy_level_medium": "Средняя — некоторые каналы подозрительны",
        "entropy_level_high": "ВЫСОКАЯ — признаки стеганографии!",
    },
    "en": {
        "app_title": "ColorCrypt — Text \u21c4 Image (v{})",
        "main_tab": "Main",
        "settings_tab": "Settings",
        "security_tab": "Security",
        "batch_tab": "Batch",
        "iii_tab": "Image-in-Image",
        "media_tab": "Media (GIF/MP4/MP3/Video)",
        "scanner_tab": "Detector",
        "debug_tab": "Debug",
        "mode_frame": "Operation Mode",
        "mode_encode": "\U0001f4c4 Text \u2192 \U0001f5bc Image (Encode)",
        "mode_decode": "\U0001f5bc Image \u2192 \U0001f4c4 Text (Decode)",
        "file_frame": "File",
        "select_file": "\U0001f4c2 Select File",
        "no_file": "No file selected",
        "file_info": "File: {} ({})",
        "content_frame": "Content",
        "progress_frame": "Progress",
        "ready": "Ready",
        "execute": "\u25b6 Execute",
        "cancel": "\u23f9 Cancel",
        "channel_frame": "Image Channel Mode",
        "channel_mono": "1-channel (R only) — max compatibility",
        "channel_rgb": "3-channel (RGB) — good compression",
        "channel_rgba": "4-channel (RGBA) — max density",
        "encode_frame": "Data Encoding Mode",
        "encode_base64": "Base64 — compatible mode",
        "compress_frame": "Data Compression (zlib)",
        "compress_enable": "Enable compression",
        "compress_level": "Compression level:",
        "format_frame": "Output Format",
        "chunk_frame": "Chunk Mode (for large files)",
        "chunk_enable": "Split into chunks",
        "chunk_size": "Chunk size:",
        "options_frame": "Additional Settings",
        "integrity": "Integrity check (SHA-256)",
        "preserve_name": "Preserve original filename",
        "lsb_label": "LSB bitness (0 = direct mode):",
        "lsb_hint": "(1-4 = LSB steganography)",
        "output_dir_frame": "Output Directory",
        "output_dir_btn": "\U0001f4c1 Select folder",
        "output_dir_default": "(next to source)",
        "encrypt_frame": "AES-256-SIV Encryption",
        "encrypt_enable": "Enable AES-256-SIV (nonce misuse resistant)",
        "password": "Password:",
        "confirm": "Confirm:",
        "gen_password": "\U0001f512 Generate Password",
        "show_password": "Show password",
        "strength_frame": "Password Strength",
        "empty_password": "\u274c Empty password",
        "hint_frame": "Password Hint",
        "hint_warn": "\u26a0\ufe0f Hints reduce security! Do not disclose your password.",
        "hint_display": "\U0001f4a1 Hint: {}",
        "encrypt_info": "\U0001f510 Encryption Info:\n\u2022 AES-256-SIV (nonce misuse resistant)\n\u2022 Argon2id (GPU-resistant, 64MB memory)\n\u2022 Random salt (16 bytes)\n\u2022 Built-in integrity check",
        "batch_add": "\u2795 Add Files",
        "batch_clear": "\U0001f5d1 Clear List",
        "batch_count": "Files: {}",
        "batch_list": "Files to Process",
        "batch_encode_all": "\u25b6 Encode All",
        "batch_decode_all": "\u25c0 Decode All",
        "debug_options": "Debug Options",
        "debug_mode": "Debug mode (verbose logging)",
        "debug_clear": "Clear log",
        "iii_container_frame": "1. Container (where to hide)",
        "iii_select_container": "\U0001f4c2 Select container image",
        "iii_not_selected": "Not selected",
        "iii_secret_frame": "2. Secret Image",
        "iii_select_secret": "\U0001f4c2 Select secret image",
        "iii_options_frame": "3. Options",
        "iii_use_alpha": "Use alpha channel",
        "iii_restore": "Restore container after decode",
        "iii_output_frame": "4. Output",
        "iii_select_output": "\U0001f4c1 Choose save path",
        "iii_not_specified": "Not specified",
        "iii_encode_btn": "\u25b6 Encode (hide secret in container)",
        "iii_decode_btn": "\u25c0 Decode (extract secret from container)",
        "iii_result_frame": "Result",
        "iii_working": "Encoding Image-in-Image...",
        "iii_decode_working": "Decoding Image-in-Image...",
        "iii_success": "\u2705 Success!",
        "iii_saved": "\U0001f4c1 Saved: {}",
        "iii_secret_size": "\U0001f532 Secret size: {}",
        "iii_alpha_saved": "   Alpha channel preserved",
        "iii_container_restored": "\u267b Container restored: {}",
        "iii_error": "\u274c Error: {}",
        "media_codecs": "Available Codecs",
        "media_no_codecs": "\u274c No codecs available",
        "media_mode_frame": "Mode",
        "media_encode_mode": "Encode (hide data in media)",
        "media_decode_mode": "Decode (extract data from media)",
        "media_codec_sel": "Media Format",
        "media_install": "Install imageio or ffmpeg",
        "media_file_frame": "File",
        "media_select_input": "\U0001f4c2 Select media file",
        "media_data_frame": "Data file (for encoding)",
        "media_select_data": "\U0001f4c2 Select data file",
        "media_output_frame": "Output",
        "media_select_output": "\U0001f4c1 Choose save path",
        "media_execute": "\u25b6 Execute",
        "scan_file_frame": "File to Scan",
        "scan_select_file": "\U0001f4c2 Select image",
        "scan_opts_frame": "Scan Parameters",
        "scan_alpha": "Scan alpha channel",
        "scan_rgb": "Scan RGB channels",
        "scan_depth": "LSB depth:",
        "scan_btn": "\U0001f50d Scan",
        "scan_result_frame": "Scan Results",
        "scan_working": "Scanning...",
        "scan_no_results": "\u274c No ColorCrypt headers found.",
        "scan_no_reasons": "Possible reasons:\n  \u2022 File contains no hidden data\n  \u2022 Data hidden with different LSB depth\n  \u2022 File was lossily re-encoded",
        "scan_found": "\u2705 Headers found: {}\n\n",
        "scan_channel": "  Channel: {}\n",
        "scan_lsb": "  LSB layers: {}\n",
        "scan_type": "  Type: {}\n",
        "scan_sig": "  Signature: {}\n",
        "scan_ver": "  Version: {}\n",
        "scan_sep": "  ---\n",
        "drop_file": "\U0001f4a1 Drop a file here",
        "drop_btn": "\U0001f4a1 Select a file",
        "err_file_not_found": "File not found",
        "err_no_file": "Please select a file first",
        "err_encrypt_no_password": "Enter a password for encryption",
        "err_password_mismatch": "Passwords do not match",
        "err_password_hint": "File is encrypted. Enter password to decrypt:",
        "err_batch_password_hint": "Some files are encrypted. Enter password:",
        "err_encode_failed": "Encoding error:\n{}",
        "err_decode_failed": "Decoding error:\n{}",
        "err_read_failed": "Could not read file:\n{}",
        "err_read_image": "Could not read image: {}",
        "err_operation_cancelled": "Operation cancelled",
        "err_select_container": "Select container and secret image",
        "err_select_output": "Specify save path",
        "err_media_no_input": "Select a media file",
        "err_media_no_data": "Select a data file",
        "err_scan_no_file": "Select a file to scan first",
        "err_batch_empty": "Add files to the list first",
        "warn_big_file": "File is large ({}). Show content?",
        "warn_large_file": "[File too large for preview]\nSize: {}",
        "warn_text_preview": "[File has {} lines, showing first 50]\n\n",
        "warn_more_lines": "\n\n... and {} more lines",
        "warn_binary": "[Binary file]\nSize: {}\nSHA-256: {}",
        "warn_text_more": "\n\n... and {} more lines",
        "encode_success": "\u2705 Encoding complete!\n\n",
        "encode_saved": "\U0001f4c1 Saved: {}\n",
        "encode_dims": "\U0001f4d0 Dimensions: {}x{}\n",
        "encode_format": "\U0001f3a8 Format: {}\n",
        "encode_file_size": "\U0001f4be File size: {}\n",
        "encode_time": "\u23f1 Time: {:.2f}s\n",
        "encode_chunks": "\n\U0001f4e6 Chunk mode: {} chunks\n",
        "encode_compress": "\U0001f5dc Compression: {}\n",
        "encode_encryption": "\U0001f510 Encryption: AES-256-SIV + Argon2id\n",
        "encode_hint_warn": "\u26a0\ufe0f WARNING: Password hints are insecure!\n   Do not use hints that reveal the password.\n\U0001f4a1 Hint: {}\n",
        "encode_sha": "\U0001f511 SHA-256: {}\n",
        "decode_success": "\u2705 Decoding complete!\n\n",
        "decode_saved": "\n\n\U0001f4c1 File saved: {}\n",
        "decode_size": "\U0001f4e6 Size: {}\n",
        "decode_chunks": "\U0001f4e6 Restored from {} chunks\n",
        "iii_use_alpha_short": "Use alpha channel",
        "iii_restore_short": "Restore container",
        "file_loaded": "\u2705 Loaded: {}",
        "image_info": "\U0001f5bc Image info:\n",
        "image_dims": "  Size: {}x{}\n",
        "image_mode": "  Mode: {}\n",
        "image_format": "  Format: {}\n\n",
        "image_decode_hint": "Press 'Execute' to decode hidden data.",
        "cancel_operation": "\u26a0\ufe0f Cancelling operation...",
        "select_encode_file": "\U0001f4c2 Select file to encode",
        "select_decode_file": "\U0001f4c2 Select image to decode",
        "encode_hint": "Supports any files (text, binary)",
        "decode_hint": "Supports PNG, WebP, BMP, TIFF, AVIF, JPEG, ZIP created by ColorCrypt",
        "batch_complete": "Complete",
        "batch_summary": "Processed files: {}\n\u2705 Success: {}\n\u274c Errors: {}",
        "password_very_strong": "\U0001f512 Very Strong",
        "password_strong": "\U0001f510 Strong",
        "password_medium": "\u26a0\ufe0f Medium",
        "password_weak": "\u26a0\ufe0f Weak",
        "password_very_weak": "\u274c Very Weak",
        "password_empty": "\u274c Empty password",
        "password_match": "\u2705 Passwords match",
        "password_no_match": "\u274c Passwords do not match",
        "pass_len_ge12": "\u2713 Length \u226512 chars",
        "pass_len_ge8": "\u2713 Length \u22658 chars",
        "pass_len_min8": "\u2717 Minimum 8 chars",
        "pass_upper": "\u2713 Has uppercase",
        "pass_no_upper": "\u2717 Add uppercase",
        "pass_lower": "\u2713 Has lowercase",
        "pass_no_lower": "\u2717 Add lowercase",
        "pass_digit": "\u2713 Has digits",
        "pass_no_digit": "\u2717 Add digits",
        "pass_special": "\u2713 Has special chars",
        "pass_no_special": "\u2717 Add special chars",
        "pass_generated": "\u2705 Random password generated and copied to clipboard",
        "lang_label": "Language:",
        "theme_label": "Dark theme",
        "select_encode": "Select file to encode",
        "select_decode_img": "Select image to decode",
        "select_container": "Select container image",
        "select_secret": "Select secret image",
        "save_as": "Save as",
        "select_media": "Select media file",
        "select_data": "Select data file",
        "select_save_as": "Save as",
        "select_scan": "Select image to scan",
        "select_output_dir": "Select output folder",
        "status_ready": "Ready",
        "status_scanning": "\u23f3 Scanning...",
        "status_error": "\u274c Error",
        "status_not_found": "\u274c Nothing found",
        "status_found_headers": "\u2705 Found {} headers",
        "media_ready": "Ready",
        "media_working": "\u23f3 Working...",
        "media_done": "\u2705 Done",
        "media_success": "\u2705 Success!\nSaved: {}",
        "media_error": "Error: {}",
        "iii_working_short": "\u23f3 Working...",
        "iii_done": "\u2705 Done",
        "notice": "Warning",
        "error": "Error",
        "iii_result_size": "  Secret size: {}x{}\n",
        "theme_applied_light": "\u2600\ufe0f Light theme",
        "theme_applied_dark": "\U0001f319 Dark theme",
        "unit_b": "B",
        "unit_kb": "KB",
        "unit_mb": "MB",
        "unit_gb": "GB",
        "unit_tb": "TB",
        "adaptive_lsb": "Adaptive K-LSB (per-channel bit depth)",
        "k_lsb_r": "R:",
        "k_lsb_g": "G:",
        "k_lsb_b": "B:",
        "k_lsb_a": "A:",
        "zip_mode": "Pack chunks into ZIP",
        "salt_label": "Salt (hex, optional):",
        "salt_hint": "(leave blank for random generation)",
        "entropy_btn": "LSB Entropy Analysis",
        "entropy_working": "Analyzing entropy...",
        "entropy_result": "LSB Entropy Results\n\n",
        "entropy_channel": "  Channel {0}: {1} zeros / {2} ones (ratio: {3:.4f})\n",
        "entropy_chi2": "    χ² = {0:.2f}, p = {1:.4f}\n",
        "entropy_suspicious": "    SUSPICIOUS: distribution too uniform (p > 0.95)\n",
        "entropy_normal": "    Natural distribution\n",
        "entropy_overall": "\nOverall verdict: {0}\n",
        "entropy_level_low": "Low — LSB appears natural",
        "entropy_level_medium": "Medium — some channels suspicious",
        "entropy_level_high": "HIGH — signs of steganography!",
    }
}
